image: maven:3.3.9-jdk-8

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

stages:
  - validate
  - test
  - build
  - artifact
  - deploy

validate:
  stage: validate
  script:
    - mvn $MAVEN_OPTS validate

unit-test:
  stage: test
  script:
    - mvn $MAVEN_OPTS test

building:
  stage: build
  script:
    - mvn $MAVEN_OPTS package -DskipTests

deploy:
  stage: deploy
  before_script:
    - git checkout master
  script:
    - git show-ref
    - git remote add heroku https://cabrini:$HEROKU_KEY@git.heroku.com/demon-automation.git
    - git push heroku HEAD:master -f
  environment:
    name: production
    url: https://demon-automation.herokuapp.com
  only:
    - master
  when: manual