image: maven:3.3.9-jdk-8

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

stages:
  - validate
  - test
  - build
  - artifact
  - deploy

validate:
  stage: validate
  script:
    - mvn validate

unit-test:
  stage: test
  script:
    - mvn test

building:
  stage: build
  script:
    - mvn package

deploy:
  stage: deploy
  script:
    - git remote add heroku https://cabrini:$HEROKU_KEY@git.heroku.com/demon-automation.git
    - git config user.name "Guilherme Cabrini da Silva"
    - git config user.email "$GITLAB_USER_EMAIL"
    - git commit -m "Heroku Deploy"
    - git push heroku HEAD:master -f
  environment:
    name: production
    url: https://demon-automation.herokuapp.com
  only:
    - master
  when: manual